jobs:
  build:
    if: github.repository == 'doocs/advanced-java'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      name: Sync To Gitee
      uses: wearerequired/git-mirror-action@master
      with:
        destination-repo: git@gitee.com:Doocs/advanced-java.git
        source-repo: git@github.com:doocs/advanced-java.git
    - continue-on-error: true
      name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
        branch: main
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: doocs/advanced-java
        gitee-username: yanglbme
name: Sync
on:
  repository_dispatch:
    types: trigger-ga___sync.yml
